### PR TITLE
Fix #70 (GraphQL schema graph neighbours issue)

### LINKED ISSUE #70: GraphQL schema creation still uses schema graph neighbour
Having turned off the "schema hopping" for resolving GraphQL queries, the schema hopping did not get turned off when generating the graphql schema.

This means that the GraphQL schema says that you *can* hop across tables, but when you send this kind of GraphQL query to bubbly it fails...

E.g. given this schema:

```hcl
table "a" { table" b" { table "c" { ... } } }
```

This graphql query is OK according to the generated schema, but it will fail because it includes a "hop"

```graphql
{
  a { c { ... }  }
}
```

The issue in the code is here:
https://github.com/valocode/bubbly/blob/0c98cd64651f224495e39bee52fb0e57fe8381b1/store/graphql.go#L48

### PR DESCRIPTION
**Pull request by olliefr**
I've made an attempt to _surgically_ isolate and remove the code related to the node hopping in the GraphQL resolver.

I think I understand what I've taken out and it's no more than is necessary while at the same time not leaving any cruft behind. And the tests pass as well. And yet, since you are the original author, @jlarfors, what's your opinion on this? 🙃 

For this PR, I recommend viewing the diff in the _unified view_. The changes then are easier to parse visually.

Closes #70

### CODE REVIEW

File: store/graphql.go [hunk 1]
```diff
@@ -165,18 +160,15 @@ func addGraphFields(t core.Table, fields map[string]gqlField) {
...
 // addGraphEdges ???
-func addGraphEdges(t core.Table, paths []schemaPath, fields map[string]gqlField) {
-	var field = fields[t.Name]
-	for _, path := range paths {
-		// We only care about the destination in the path and whether it is scalar.
-		// The middle or passing edges will be included as their own paths
+func addGraphEdges(n *schemaNode, fields map[string]gqlField) {
+	var field = fields[n.table.Name]
+
+	for _, edge := range n.edges {
```
Comment (jlarfors) [inline store/graphql.go:166]: Great :)

**Review by jlarfors — APPROVED** [review]
LGTM

**Review by benmarsden — APPROVED** [review]
